[global]
# Development mode
developmentMode = true

[server]
# Server settings
port = 8501
headless = false
enableCORS = false
enableXsrfProtection = false

[browser]
# Browser settings
gatherUsageStats = false

[theme]
# Theme settings
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
# Client settings
showErrorDetails = true
